import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import "./globals.css";
import Tabs from "@/components/Tabs";
import BottomTabs from "@/components/Bottomtab"; // 경로 맞게 조정
import { Typography, Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                gap: {
                  xs: "10px",
                  sm: "20px",
                  lg: "30px",
                },
                padding: {
                  xs: "2vh 4vw",
                  sm: "4vh 6vw",
                  lg: "4vh 12vw",
                },
                maxWidth: "100vw",     // 너비 넘침 방지
                overflowX: "hidden",    // 가로 스크롤 방지
                boxSizing: "border-box", // 패딩 포함 크기 계산
              }}
            >
              <header>
                <div
                  style={{
                    // display: "flex",
                    // alignItems: "right",
                    // justifyContent: "space-between",
                    display: "flex",
                    flex: 1,
                    padding: "20px 0",
                    paddingTop: "20px",
                  }}
                >
                  {/* ✅ AIM Lab 로고 삽입 */}
                  <a href="/" style={{ display: "flex", alignItems: "right", gap: "10px" }}>
                    <Box
                      component="img"
                      src="https://github.com/shwang45/shblog/blob/main/img/aim_logo2.png?raw=true"
                      alt="AIM Lab Logo"
                      sx={{
                        height: "100px",
                        objectFit: "contain",
                        display: {
                          xs: "none",   // 📱 모바일에서는 안 보임
                          sm: "block",  // 💻 태블릿 이상에서 보임
                        },
                      }}
                    />
                  </a>
                </div>
                <Tabs />
                <BottomTabs />
              </header>
              <div style={{ display: "flex", flex: 1, padding: "20px 0", paddingTop: "20px" }}>
                {children}
              </div>
              <footer>
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "flex-end",
                  }}
                >
                  <Typography variant="body2">
                    Published with
                    <a href="https://pages.github.com">GitHub Pages</a>
                  </Typography>
                  <Typography variant="caption" style={{ fontStyle: "italic" }}>
                    And special thanks to my best frd, Song
                  </Typography>
                </div>
              </footer>
              
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
